//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expanse_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catagory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catagory()
        {
            this.expenses = new HashSet<expense>();
        }
    
        public int catagory_id { get; set; }
        public string catagory_name { get; set; }
        public Nullable<decimal> catagory_limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expense> expenses { get; set; }
    }
}
