//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expanse_Manager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class expensedbEntities2 : DbContext
    {
        public expensedbEntities2()
            : base("name=expensedbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catagory> catagories { get; set; }
        public virtual DbSet<expense> expenses { get; set; }
        public virtual DbSet<total_limit> total_limit { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
