//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expanse_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int expense_id { get; set; }
        public string Title { get; set; }
        public string Discription { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string catagory { get; set; }
    }
}
