//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expanse_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_limit
    {
        public int total_id { get; set; }
        public Nullable<decimal> total_limit1 { get; set; }
    }
}
